CFLAGS = -g

all: Algo.c 268_Missing.c 41.FirstMissingPositive.c Algo.h 
#	$(CC) $(CFLAGS) -o missing Algo.c 268_Missing.c
#	$(CC) $(CFLAGS) -o missing_positive Algo.c 41.FirstMissingPositive.c
#	$(CC) $(CFLAGS) -o set_mismatch Algo.c 645.SetMismatch.c
	$(CC) $(CFLAGS) -o find_duplicate Algo.c 287.FindtheDuplicateNumber.c

clean:
	rm missing
